# Generated by Django 5.1.5 on 2025-02-05 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="studentAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_name", models.CharField(max_length=100)),
                ("student_id", models.CharField(max_length=50)),
                ("question_number", models.IntegerField()),
                ("extracted_text", models.TextField()),
                ("uploaded_file", models.FileField(upload_to="student_answers/")),
                ("score", models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="MarkingScheme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.IntegerField()),
                ("extracted_text", models.TextField()),
                ("uploaded_file", models.FileField(upload_to="marking_scheme/")),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
