# Generated by Django 5.1.5 on 2025-02-07 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="markingscheme",
            name="teacher",
        ),
    ]
