# Generated by Django 5.1.5 on 2025-02-08 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0002_remove_markingscheme_teacher"),
    ]

    operations = [
        migrations.RenameField(
            model_name="studentanswer",
            old_name="question_number",
            new_name="question",
        ),
    ]
