# Generated by Django 5.1.5 on 2025-02-08 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0003_rename_question_number_studentanswer_question"),
    ]

    operations = [
        migrations.RenameField(
            model_name="studentanswer",
            old_name="question",
            new_name="question_number",
        ),
    ]
